name: Integration Test Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup NodeJs
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Check Docker
        run: docker --version
      
      - name: Check Docker Compose version
        run: docker compose --version
      
      - name: Copy env variable
        run: cp .env.example .env

      - name: Install Dependencies
        run: npm Install

      - name: Run Integration Test
        run: npm run test:integration