services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
  
  backend:
    build: .
    container_name: backend-app
    ports:
      - 3000:3000
    depends_on:
      - mongodb
    environment:
      MONGO_URL: mongodb://mongodb:27017

volumes:
  mongodb_data:
